/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:918574:
  appc.background(230);
} //_CODE_:window1:918574:

public void timer(GButton source, GEvent event) { //_CODE_:startTimer:648558:
  println("startTimer - GButton >> GEvent." + event + " @ " + millis());
  
  
  

  if (timer.timerStart == false) {
    startTimer.setText("Pause");
    timer.timerStart = true; 
  } else if (timer.timerStart == true) {
    
        startTimer.setText("Resume");

    timer.timerStart = false;
  }







} //_CODE_:startTimer:648558:

public void lofiButtonPressed(GButton source, GEvent event) { //_CODE_:lofiMusic:351987:
  currentMusic.stop();
  currentMusic = fileLofi;
  currentMusic.play();
} //_CODE_:lofiMusic:351987:

public void pianoButtonPressed(GButton source, GEvent event) { //_CODE_:pianoMusic:529890:

  currentMusic.stop();
  currentMusic = fileClassical;
  currentMusic.play();
} //_CODE_:pianoMusic:529890:

public void jazzButtonPressed(GButton source, GEvent event) { //_CODE_:jazzMusic:741816:
    currentMusic.stop();
    currentMusic = fileJazz; 
    
    currentMusic.play();

} //_CODE_:jazzMusic:741816:

public void volumeSliderPressed(GSlider source, GEvent event) { //_CODE_:volumeSlider:449108:
  volume = volumeSlider.getValueF();
  currentMusic.amp(volume);
} //_CODE_:volumeSlider:449108:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 500, 500, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  startTimer = new GButton(window1, 37, 45, 80, 30);
  startTimer.setText("Start Timer");
  startTimer.addEventHandler(this, "timer");
  lofiMusic = new GButton(window1, 41, 271, 118, 30);
  lofiMusic.setText("Play Lofi Music");
  lofiMusic.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  lofiMusic.addEventHandler(this, "lofiButtonPressed");
  pianoMusic = new GButton(window1, 42, 323, 117, 30);
  pianoMusic.setText("Play Piano Music");
  pianoMusic.addEventHandler(this, "pianoButtonPressed");
  jazzMusic = new GButton(window1, 42, 373, 117, 30);
  jazzMusic.setText("Play Jazz Music");
  jazzMusic.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  jazzMusic.addEventHandler(this, "jazzButtonPressed");
  volumeSlider = new GSlider(window1, 40, 423, 124, 40, 10.0);
  volumeSlider.setLimits(1.0, 0.0, 1.0);
  volumeSlider.setNumberFormat(G4P.DECIMAL, 0);
  volumeSlider.setOpaque(false);
  volumeSlider.addEventHandler(this, "volumeSliderPressed");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GButton startTimer; 
GButton lofiMusic; 
GButton pianoMusic; 
GButton jazzMusic; 
GSlider volumeSlider; 
